"use client";
import Link from "next/link";
import { createContext, useContext, useState, type FormEvent, type ReactNode } from "react";

export type CartItem = { name: string; price: number; image: string; quantity: number };
type CartContextValue = { items: CartItem[]; count: number; subtotal: number; add: (item: Omit<CartItem, "quantity">) => void; change: (name: string, amount: number) => void };
const CartContext = createContext<CartContextValue | null>(null);
const links = [{ href: "/", label: "Start" }, { href: "/geschichte", label: "Geschichte" }, { href: "/produkte", label: "Produkte" }, { href: "/kontakt", label: "Kontakt" }];

export function useCart() { const context = useContext(CartContext); if (!context) throw new Error("useCart muss innerhalb von SiteShell verwendet werden."); return context; }

export function SiteShell({ children }: { children: ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [cartOpen, setCartOpen] = useState(false);
  const [orderOpen, setOrderOpen] = useState(false);
  const [sent, setSent] = useState(false);
  const [cart, setCart] = useState<Record<string, CartItem>>({});
  const items = Object.values(cart);
  const count = items.reduce((total, item) => total + item.quantity, 0);
  const subtotal = items.reduce((total, item) => total + item.price * item.quantity, 0);
  const add = (item: Omit<CartItem, "quantity">) => setCart(current => ({ ...current, [item.name]: { ...item, quantity: (current[item.name]?.quantity || 0) + 1 } }));
  const change = (name: string, amount: number) => setCart(current => { const item = current[name]; if (!item) return current; const quantity = item.quantity + amount; if (quantity <= 0) { const next = { ...current }; delete next[name]; return next; } return { ...current, [name]: { ...item, quantity } }; });
  const formatPrice = (price: number) => `${price.toLocaleString("de-DE")} €`;
  const summary = items.map(item => `${item.name} — ${item.quantity} × ${formatPrice(item.price)}`).join("\n");
  function submitOrder(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name") || ""); const email = String(form.get("email") || ""); const message = String(form.get("message") || ""); const body = [`Name: ${name}`, `E-Mail: ${email}`, "", "Bestellübersicht:", summary, `Zwischensumme: ${formatPrice(subtotal)}`, "", "Nachricht:", message].join("\n"); window.location.href = `mailto:kontakt@shinrin-bonsai.de?subject=${encodeURIComponent("Bestellanfrage über shinrin-bonsai.de")}&body=${encodeURIComponent(body)}`; setSent(true); }

  return <CartContext.Provider value={{ items, count, subtotal, add, change }}><>
    <header className="site-header"><div className="container header-inner"><Link href="/" className="logo"><img src="/assets/images/logo-icon.png" alt="Shinrin Bonsai Logo" />Shinrin Bonsai</Link><nav className="main-nav"><ul>{links.map(link => <li key={link.href}><Link href={link.href}>{link.label}</Link></li>)}</ul></nav><div className="header-actions"><button className="cart-button" onClick={() => setCartOpen(true)} aria-label={`Warenkorb öffnen, ${count} Artikel`}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 6h2l2.4 12.2a2 2 0 0 0 2 1.8h7.6a2 2 0 0 0 2-1.6L21 8H6" /><circle cx="10" cy="21" r="1" /><circle cx="17" cy="21" r="1" /></svg><span className="cart-count">{count}</span></button><button className="burger" onClick={() => setMobileOpen(true)} aria-label="Menü öffnen">☰</button></div></div></header>
    {mobileOpen && <nav className="mobile-nav" style={{ display: "block", position: "fixed", inset: 0, zIndex: 20, background: "var(--bg)", padding: "40px 24px" }}><button className="icon-button" onClick={() => setMobileOpen(false)} aria-label="Menü schließen">×</button><ul style={{ display: "grid", gap: 24, listStyle: "none", padding: 0, marginTop: 48 }}>{links.map(link => <li key={link.href}><Link href={link.href} onClick={() => setMobileOpen(false)} style={{ font: "2rem var(--display)" }}>{link.label}</Link></li>)}</ul></nav>}
    {cartOpen && <div role="presentation" onClick={() => setCartOpen(false)} style={{ position: "fixed", inset: 0, zIndex: 30, background: "rgba(36, 30, 28, .28)", backdropFilter: "blur(3px)" }}><aside role="dialog" aria-label="Warenkorb" onClick={event => event.stopPropagation()} style={{ position: "absolute", top: 0, right: 0, width: "min(430px, 100%)", height: "100%", background: "rgba(249, 249, 249, .97)", padding: 32, overflowY: "auto", boxShadow: "-12px 0 32px rgba(36,30,28,.12)" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><h2 style={{ margin: 0 }}>Warenkorb</h2><button className="icon-button" onClick={() => setCartOpen(false)} aria-label="Warenkorb schließen">×</button></div>{items.length === 0 ? <p>Ihr Warenkorb ist noch leer.</p> : <>{items.map(item => <div key={item.name} style={{ display: "grid", gridTemplateColumns: "64px 1fr auto", gap: 12, alignItems: "center", borderBottom: "1px solid var(--line)", padding: "16px 0" }}><img src={item.image} alt="" style={{ width: 64, height: 64, objectFit: "cover", borderRadius: 10 }} /><div><strong>{item.name}</strong><div style={{ color: "var(--grey)", fontSize: ".86rem" }}>{formatPrice(item.price)}</div><div><button className="filter-pill" onClick={() => change(item.name, -1)} aria-label="Menge verringern">−</button> {item.quantity} <button className="filter-pill" onClick={() => change(item.name, 1)} aria-label="Menge erhöhen">+</button></div></div><strong>{formatPrice(item.price * item.quantity)}</strong></div>)}<div style={{ display: "flex", justifyContent: "space-between", marginTop: 24, fontSize: "1.1rem" }}><span>Zwischensumme</span><strong>{formatPrice(subtotal)}</strong></div><p style={{ fontSize: ".8rem", color: "var(--grey)" }}>Keine Zahlung im Shop — der Warenkorb wird als Bestellanfrage per E-Mail übermittelt.</p><button className="btn btn-primary" style={{ width: "100%" }} onClick={() => setOrderOpen(true)}>Bestellanfrage senden →</button></>}</aside></div>}
    {orderOpen && <div role="presentation" onClick={() => setOrderOpen(false)} style={{ position: "fixed", inset: 0, zIndex: 40, background: "rgba(36, 30, 28, .32)", backdropFilter: "blur(3px)", display: "grid", placeItems: "center", padding: 24 }}><div role="dialog" aria-modal="true" aria-labelledby="order-title" onClick={event => event.stopPropagation()} style={{ width: "min(540px, 100%)", maxHeight: "90vh", overflowY: "auto", background: "var(--paper)", borderRadius: 14, padding: 32 }}>{sent ? <><h2 id="order-title">E-Mail-Programm wird geöffnet</h2><p>Die Anfrage ist vorbereitet — bitte im geöffneten E-Mail-Programm absenden, um sie zu übermitteln.</p><button className="btn btn-ghost" onClick={() => { setOrderOpen(false); setSent(false); }}>Schließen</button></> : <><div style={{ display: "flex", justifyContent: "space-between" }}><h2 id="order-title">Anfrage abschicken</h2><button className="icon-button" onClick={() => setOrderOpen(false)} aria-label="Formular schließen">×</button></div><p>Eine kurze Nachricht genügt — der Warenkorb-Inhalt wird automatisch mitgeschickt. Antworten kommen persönlich, meist innerhalb weniger Tage.</p><form className="form" onSubmit={submitOrder}><label htmlFor="order-name">Name</label><input id="order-name" name="name" required autoComplete="name" /><label htmlFor="order-email">E-Mail</label><input id="order-email" name="email" type="email" required autoComplete="email" /><label htmlFor="order-message">Nachricht (optional)</label><textarea id="order-message" name="message" placeholder="z. B. Wunsch-Lieferzeitraum, Fragen zur Pflege …" /><label>Bestellübersicht</label><pre style={{ whiteSpace: "pre-wrap", background: "rgba(96,114,90,.06)", padding: 16, borderRadius: 10, font: ".86rem var(--body)" }}>{summary}</pre><button className="btn btn-primary" type="submit">Anfrage per E-Mail senden →</button></form></>}</div></div>}
    {children}
    <footer className="footer"><div className="container"><div className="footer-grid"><div className="footer-brand"><Link href="/" className="logo"><img src="/assets/images/logo-icon.png" alt="Shinrin Bonsai Logo" />Shinrin Bonsai</Link><p>Geduld, die wächst. Bonsai mit Herz gezogen.</p></div><div><h4>Navigation</h4><div className="footer-links">{links.slice(0, 3).map(link => <Link key={link.href} href={link.href}>{link.label}</Link>)}</div></div><div><h4>Service</h4><div className="footer-links"><Link href="/kontakt">Kontakt</Link><Link href="/#vertrauen">Pflegehinweise</Link><span>Versand</span></div></div><div><h4>Rechtliches</h4><div className="footer-links"><Link href="/impressum">Impressum</Link><span>Datenschutz</span></div></div></div><div className="footer-bottom">© 2026 Shinrin Bonsai. Alle Rechte vorbehalten.</div></div></footer>
  </></CartContext.Provider>;
}
